import { type BackgroundLayer } from '@core/model/background-layer';

export const SCENE_GAME_MAP_UNDERGROUND_BACKGROUND_OTHER: BackgroundLayer = {
  index: 1,
  tiles: [
    /*
    [],
    [
      undefined,
      {spriteX: 0, spriteY: 0, tileset: 'tileset_grass'},
      {spriteX: 0, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 0, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 0, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 0, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 0, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 0, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 0, spriteY: 2, tileset: 'tileset_grass'},
    ],
    [
      undefined,
      {spriteX: 1, spriteY: 0, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 2, tileset: 'tileset_grass'},
    ],
    [
      undefined,
      {spriteX: 1, spriteY: 0, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 2, tileset: 'tileset_grass'},
    ],
    [
      undefined,
      {spriteX: 1, spriteY: 0, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 2, tileset: 'tileset_grass'},
    ],
    [
      undefined,
      {spriteX: 1, spriteY: 0, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 2, tileset: 'tileset_grass'},
    ],
    [
      undefined,
      {spriteX: 1, spriteY: 0, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 2, tileset: 'tileset_grass'},
    ],
    [
      undefined,
      {spriteX: 1, spriteY: 0, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 1, spriteY: 2, tileset: 'tileset_grass'},
    ],
    [
      undefined,
      {spriteX: 2, spriteY: 0, tileset: 'tileset_grass'},
      {spriteX: 2, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 2, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 2, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 2, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 2, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 2, spriteY: 1, tileset: 'tileset_grass'},
      {spriteX: 2, spriteY: 2, tileset: 'tileset_grass'},
    ],
    */
  ],
};
